# upptime configuration
owner: whydarcy
repo: upptime-sile-games
site: https://whydarcy.github.io/upptime-sile-games
status-website: true
commit-message: "⚡ Обновление статуса"

# Частота проверок (каждые 5 минут)
schedule: "*/5 * * * *"

# Логика инцидентов
daysUntilClose: 7
response-time-critical: 5000
response-time-warning: 3000

# Сервисы
sites:
  - name: 🌐 Основной сайт
    url: https://silegta.ru

  - name: 💬 Форум
    url: https://forum.silegta.ru

  - name: 📡 CDN 1 (launcher.whydarcy.ru)
    url: https://launcher.whydarcy.ru

  - name: 📡 CDN 2 (sile-launcher-update.sile.group)
    url: https://sile-launcher-update.sile.group

  - name: 🧱 SILE GROUP сборки
    url: https://sile.group
